baseURL = "https://blog.negbie.space"
title = ""
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "negbie's blog"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "build with hugo"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = true
  showReadTime = false

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "negbie"

[author.social]
  codepen = ""
  email = ""
  facebook = ""
  github = "negbie"
  instagram = ""
  twitter = "eugen_apk"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "GitHub"
  weight = -70
  identifier = "repository"
  url = "https://github.com/negbie"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
